## Numpy Questions

## 1Q. Arrays
Given a space separated list of numbers. Print a reversed NumPy array with the element type float.

In [2]:
import numpy as np

def arrays(arr):
    return(np.array(arr[::-1], float))# complete this function

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 -1 -2 -3 -4 -5
[-5. -4. -3. -2. -1.  5.  4.  3.  2.  1.]


## 2Q. Shape and Reshape
Given a space separated list of nine integers. Task is to convert this list into a 3X3 NumPy array.

In [3]:
import numpy as np 
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3Q. Transpose and flatten
Given a NXM integer array matrix with space separated elements (N = rows and M = columns).
Task is to print the transpose and flatten results.

In [1]:
import numpy as np

n,m = map(int,input().split())
arr = np.array([input().strip().split() for _ in range(n)],int)

print(arr.transpose())
print(arr.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## 4Q. Concatenate


In [2]:
import numpy as np

a,b,c = map(int,input().split())
arr_A = np.array([input().strip().split() for _ in range(a)],int)
arr_B = np.array([input().strip().split() for _ in range(b)],int)

print(np.concatenate((arr_A,arr_B),axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## 5Q. Zeros and Ones


In [4]:
import numpy as np

n = tuple(map(int,input().split()))

print(np.zeros(n, dtype = np.int))
print(np.ones(n,dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## 6Q. Eye and Identity


In [5]:
import numpy as np
n,m = map(int,input().split())
np.set_printoptions(legacy = '1.13')
print(np.eye(n,m))

5 5
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


## 7Q. Array Mathematics

In [6]:
import numpy as np

n,m = map(int,input().split())
A = np.array([list(map(int,input().split())) for _ in range(n)],int)
B = np.array([list(map(int,input().split())) for _ in range(n)],int)
print(np.add(A,B),np.subtract(A,B),np.multiply(A,B),np.floor_divide(A,B)
      ,np.mod(A,B),np.power(A,B),sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## 8Q. Floor, ceil and rint

In [7]:
import numpy as np

np.set_printoptions(legacy = '1.13')
l = list(map(float,input().split()))
arr = np.array(l)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## 9Q. Sum and prod

In [8]:
import numpy as np

n,m = map(int,input().split())
A = np.array([input().split() for _ in range(n)],int)
print(np.prod(np.sum(A,axis=0),axis=0))

2 2
1 2
3 4
24


## 10Q.Min and Max

In [9]:
import numpy as np

n,m = map(int,input().split())
list1 = []
for i in range(n):
    l =list(map(int,input().split()))
    list1.append(l)
arr = np.array(list1)
print(np.max(np.min(arr,axis = 1)))

4 2
1 2
3 4
5 6
7 8
7


## 11Q. Mean, var and Std

In [11]:
import numpy as np

np.set_printoptions(sign=" ")
n, m = list(map(int, input().split()))
arr = np.array([input().split() for i in range(n)], dtype=int)
print(np.mean(arr, axis=1))
print(np.var(arr, axis=0))
output = np.std(arr)
print(output.round(12))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## 12Q. Dot and Cross

In [12]:
import numpy as np

n = int(input())
A = np.array([input().split() for i in range(n)],int)
B = np.array([input().split() for i in range(n)],int)
print(A.dot(B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## 13Q. Inner and Outer

In [13]:
import numpy as np

a = np.array(input().split(),int)
b = np.array(input().split(),int)
print(np.inner(a,b))
print(np.outer(a,b))

1 2
3 4
11
[[3 4]
 [6 8]]


## 14Q. Polynomials

In [14]:
import numpy as np

l = list(map(float,input().split()))
n = int(input())
arr = np.array(l)
print(np.polyval(arr,n))

1.2 3 4
0
4.0


## 15Q. Linear Algebra

In [15]:
import numpy as np

n = int(input())
arr = np.array([input().split() for i in range(n)],dtype=float)
detv = np.linalg.det(arr)
print(detv.round(2))

2
1.1 1.1
1.1 1.1
0.0
